### ISSUE TITLE
ndk dependancies 

### ISSUE THREAD

**Issue by scottyab** [scottyab/rootbeer#1]
Sort out the ndk dependancies to build with gradle, maybe use https://github.com/nhachicha/android-native-dependencies

**Comment by stealthcopter** [comment]
I have addressed this issue in a new branch [ndk-update](https://github.com/scottyab/rootbeer/tree/feature/ndk-update). This uses a newer gradle version / android studio to compile external native cpp files without the need for a 3rd party dependency or resorting to using the command line.

**Comment by stealthcopter** [comment]
Fixed with commit cfd9e8325845910f06a6d26f51f39fefd7304d36
