### ISSUE TITLE
64bit support

### ISSUE THREAD

**Issue by biddster** [scottyab/rootbeer#10]
Using rootbeer on a 64bit device (Nexus 6P) and I get an exception saying the native library is missing. 

I'll look to provide a PR with a fix.

**Comment by biddster** [comment]
Can't see for looking, 64bit libs are in there. I'll try harder and try to get to the bottom of it. It's working on everything other than my 6P.

**Comment by biddster** [comment]
Ah, got it, rootbeerlib/jni/build.sh doesn't copy the 64bit libs into the source tree. Consequently, the native libs don't make it into the aar.

**Comment by scottyab** [comment]
good spot

**Comment by biddster** [comment]
I'll throw you a PR for a fix.

**Comment by scottyab** [comment]
Thanks @biddster :+1:
