### ISSUE TITLE
samsung s8 return true for not rooted device 

### ISSUE THREAD

**Issue by samudini** [scottyab/rootbeer#100]
i have used rootBeer.isRooted() method it return true for non rooted device  SAMSUNG S8

**Comment by DebdeepG** [comment]
Can you provide some logs with the filter - "RootBeer"?

**Comment by stealthcopter** [comment]
In the upcoming release we've removed busybox from the default root checks, this should hopefully fix many of the problems with false positives. I'm closing this issue but please re-open if you get a false positive with 0.0.8 onwards.
Thanks!
