### ISSUE TITLE
support android Q?

### ISSUE THREAD

**Issue by munki1992** [scottyab/rootbeer#102]
Hello. I have a question and ask a question.
This time, the use of getExternalStorageDirectory () in Android Q has been deprecated. I don't know if you are using getExternalStorageDirectory (), but do you support Q?

**Comment by scottyab** [comment]
Thanks for the question. We don't use `getExternalStorageDirectory()` in RootBeer and yes RootBeer is supported in Android 10 a.k.a Android Q
