### ISSUE TITLE
Fix CI setup

### ISSUE THREAD

**Issue by stealthcopter** [scottyab/rootbeer#106]
Circle CI stopped working due to 1.0 being deprecated, should be an easy fix to update it to 2.0.
Prob also need to change the sdk image version in the config.

**Comment by scottyab** [comment]
an alternative to look at move to Bitrise.io?

**Comment by stealthcopter** [comment]
CircleCI is working again :) Can look at moving to Bitrise.io if either of us has some extra time ever :laughing:
