### ISSUE TITLE
Root check stucks on Android 10 (security patch level: November 5, 2019)

### ISSUE THREAD

**Issue by oleksandrbalan** [scottyab/rootbeer#107]
Hi!

Thank you for your library, we were using it for some time, but it does not seem to work properly with the latest security patch.

Method `checkForRWPaths` is stuck due to waiting for response from `mountReader` method.
Not sure, but maybe there is a problem with executing `mount` command.

Tested on non-rooted Pixel 2.

**Comment by stealthcopter** [comment]
@scottyab Can you test this on an Android 10 device?

**Comment by scottyab** [comment]
hmmm, I'm not seeing this behaviour.  @oleksandrbalan can you provide any extra context? 

![screenshot-1575042753342](https://user-images.githubusercontent.com/404105/69879798-4e020f00-12c0-11ea-9963-d9e039385a2b.jpg)
![screenshot-1575042739483](https://user-images.githubusercontent.com/404105/69879800-4e9aa580-12c0-11ea-847d-9908263329c1.jpg)

**Comment by oleksandrbalan** [comment]
@scottyab Huh, cannot reproduce it now 😱Everything works as expected. I think we can close it, sorry for confusions :(

**Comment by scottyab** [comment]
no worries @oleksandrbalan
