### ISSUE TITLE
False Positive FireOS device KFSAWI

### ISSUE THREAD

**Issue by aloz77** [scottyab/rootbeer#109]
Maybe much more Fire OS devices affected

`V/RootBeer: RootBeer: checkForBinary() [184] - /system/xbin/busybox binary detected!`

**Comment by scottyab** [comment]
We're thinking about taking the busybox binary check out of the main `isRooted()` check given it generates so many false positives.

**Comment by DebdeepG** [comment]
Actually `isRooted()` screwed me up as my code went onto production. Many users with chinese roms such as Oppo were affected even though they had purchased a fresh device. Seems like busybox binary is being left over by some of the OEM manufacturers.

Best case is to leave the busybox check apart.

**Comment by stealthcopter** [comment]
In the upcoming release we've removed busybox from the default root checks, this should hopefully fix many of the problems with false positives. I'm closing this issue but please re-open if you get a false positive with 0.0.8 onwards.
Thanks!
