### ISSUE TITLE
Nexus devices evaluated as rooted

### ISSUE THREAD

**Issue by hudys** [scottyab/rootbeer#11]
Hi, 

Im getting this result on Nexus 5, Nexus 5X and Nexus 6. None of these devices is rooted. How is that possible?

![screen shot 2016-03-04 at 16 45 36](https://cloud.githubusercontent.com/assets/5392257/13571687/d959572e-e476-11e5-975f-4fce696f35af.png)

**Comment by scottyab** [comment]
Hey @hudys, thanks for the report. From the screenshot, it looks like you are getting positive results for root from testkeys, dangerous properties and finding su binary. 
* It would be useful to hear the path of the detected su binary (line:172 of Rootbeer.java)
* What's your `android.os.Build.TAGS`  (line 58 of Rootbeer.java)
* What are the values reported of `ro.debuggable` or `ro.secure` (line 224,225 of Rootbeer.java) 

Might also help to attach the device info results from [an app](https://play.google.com/store/apps/details?id=com.devicestats.android)

**Comment by hudys** [comment]
- android.os.Build.TAGS - release-keys
- ro.debuggable = 1, ro.secure = 0
- I have also tried add breakpoint to line 176 but it didn't catch anything

**Comment by scottyab** [comment]
should be fixed in #18
