### ISSUE TITLE
Security flag from Rootbeer

### ISSUE THREAD

**Issue by abunur** [scottyab/rootbeer#113]
This comes up in three different places in the Rootbeer library, when scanning with Veracode's security tools (I've provided the actual classes / line numbers below after the flaw explanation):

Improper Output Neutralization for Logs CWE ID 117 

Description
A function call could result in a log forging attack. Writing untrusted data into a log file allows an attacker to forge log entries or inject malicious content into log files. Corrupted log files can be used to cover an attacker's tracks or as a delivery mechanism for an attack on a log viewing or processing utility. For example, if a web administrator uses a browser-based utility to review logs, a cross-site scripting attack might be possible.
Recommendations
Avoid directly embedding user input in log files when possible. Sanitize untrusted data used to construct log entries by using a safe logging mechanism such as the OWASP ESAPI Logger, which will automatically remove unexpected carriage returns and line feeds and can be configured to use HTML entity encoding for non-alphanumeric data. Only write custom blacklisting code when absolutely necessary. Always validate untrusted input to ensure that it conforms to the expected format, using centralized data validation routines when possible.

 com/.../rootbeer/util/QLog.java 47 | 
 com/.../rootbeer/util/QLog.java 48 | 
 com/.../rootbeer/util/QLog.java 82 | 

Here is a link to cleansing functions they recommend (scroll down for the Java section):
https://help.veracode.com/reader/4EKhlLSMHm5jC8P8j3XccQ/IiF_rOE79ANbwnZwreSPGA

**Comment by stealthcopter** [comment]
Hi @abunur I've had a quick look I don't think the Android Log functions are vulnerable to injection as unlike traditional java log files they can contain newline chars without any issue. This seems like it's a false positive from the scanner. However if you can find any evidence that shows log injection is possible on android please update us!

**Comment by abunur** [comment]
Thanks for the feedback Scott!

Fuad Kamal
Anaara LLC
www.anaara.com
240.515.7578 (m)
twitter: @flexRonin
author, The Kotlin Book: http://thekotlinbook.com
co-author, Android Apprentice. Technical Editor, Saving Data on Android
RayWenderlich.com Team member, https://www.raywenderlich.com/u/abunur
behance: https://www.behance.net/fuadkamal
linkedIn: linkedin.com/in/anaara
photography: https://fuadkamal.org

**Comment by stealthcopter** [comment]
No problem, thanks for bringing it up

Mat - the other developer ;)

**Comment by abunur** [comment]
so sorry, Matt! I had replied from my email, it didn't show me your name there. 🤦🏽‍♂️

**Comment by stealthcopter** [comment]
no problem, only mentioned it to avoid confusion :)
