### ISSUE TITLE
new 0.0.8 release?

### ISSUE THREAD

**Issue by pdarcos** [scottyab/rootbeer#114]
Hi everyone,

Great project!

This project seems to still be active yet there's no new release since mid 2018 with version 0.0.7...

Any reason for there being no new releases in almost 2 years? Any plans on releasing 0.0.8 anytime soon?

Cheers

**Comment by scottyab** [comment]
Hey @pdarcos Thanks for the interest. Yep, we're kinda active just suffer from time deficiency ;) Matt and I are looking to allocate some time in 2020 to updating and adding new checks.
