### ISSUE TITLE
Detect Magisk's Icon

### ISSUE THREAD

**Issue by danielzgtg** [scottyab/rootbeer#115]
Magisk itself might not be detectable, but as long as Magisk Manager can be found in the launcher, it will leave a trace.

Tapping "Hide Magisk Manager" scrambles the package name and replaces the name with a generic "Manager" (all languages). However, the app icon stays the same.

Therefore, for `CheckRootManagementApps`, we can do something like this:
```
FINGERPRINT = "0123456789" // Hash of Magisk's icon

hasMagiskIcon() {
    for (app : apps) {
        if ("Manager" not in app.name) continue
        bitmap = render(app.icon, "mdpi")
        if (hash(bitmap) == FINGERPRINT) return true
    }
    return false
}
```

**Comment by scottyab** [comment]
I like you're thinking 👍 , it could work as an indicator. It feels fairly open to being circumvented if the Magisk icon is updated (leaving the hash out of date). If we create a set of checks specifically focused on detecting Magisk this could live with them. Thanks for the idea and of course would welcome a PR

**Comment by stealthcopter** [comment]
@danielzgtg This is a very cool idea! I'm going to assign this to me and have a go at it :)

**Comment by Zelgadiss** [comment]
> Manager
Scrambled name can be anything in newest versions of Magisk

**Comment by stealthcopter** [comment]
I've written a class that can perform this. Can anyone test it on their devices to see if it generates the same fingerprint? you only need to install magisk manager (rooting phone is not required). We will need to at least generate a fingerprint for all different display densities.

**How it works**
1. Get's app icon drawable
2. Convert to bitmap
3. Compress bitmap to png byte array
4. MD5 png byte array
5. Compare to fingerprint

This assumes that this entire process is deterministic, if this isn't the case, we're going to have difficulty calculating a fingerprint that is consistent across devices. If the png compression is the issue we may be able to hash the bitmap directly with something like the following:

```java
int hash(Bitmap bitmap){
   int[] buffer = new int[bitmap.getWidth(), bitmap.getHeight()];
   bitmap.getPixels(buffer, 0, 0, 0, 0, bitmap.getWidth(), bitmap.getHeight());
   return Arrays.hashCode(buffer);
}
```

**Note**
This will only work until magisk catch on and start messing with their logo when hiding, but it is a fun little cat and mouse game we play :)

**Source**
https://github.com/scottyab/rootbeer/blob/feature/magisk-detection/rootbeerlib/src/main/java/com/scottyab/rootbeer/invasive/MagiskDetect.java

**Comment by danielzgtg** [comment]
Magisk Manager no longer has an icon
