### ISSUE TITLE
Kingo Root

### ISSUE THREAD

**Issue by jacobvyn** [scottyab/rootbeer#118]
I Did not find  Kingo Root app id among those you check when testing if the device rooted 
https://www.kingoapp.com/tag/google/

**Comment by stealthcopter** [comment]
Thanks for pointing this out, I've found the package name of this and a few other root tools we should add to our list

```
com.kingroot.kinguser
com.kingo.root
com.smedialink.oneclickroot
com.zhiqupk.root.global
com.alephzain.framaroot
```

**Comment by scottyab** [comment]
🤔 should we just look for *root* in the AppId/package name?

**Comment by stealthcopter** [comment]
@scottyab no, because then the example app would flag itself ;) I think there would be too many false positives if we were to do this.

**Comment by stealthcopter** [comment]
These packages have been added and will be in the upcoming 0.0.8 release :)
