### ISSUE TITLE
printstackTrace used in this library. 

### ISSUE THREAD

**Issue by anshulkabramobisy** [scottyab/rootbeer#123]
There are a couple of instances available in this library, which prints StackTrace in the catch block. We have used this lib in production, and the audit team as reported these issues to ignore this lib.
Ideally, any standard library should not print such stackTraces.  Please remove them to avoid such audit-related issues.

**Comment by stealthcopter** [comment]
Hi @anshulkabramobisy, thanks for your report! I will replace the instances of `printStackTrace` with calls to our logging class, which then can be disabled via the exposed `setLogging(false)`. I'll get this added for the upcoming 0.0.8 release

**Comment by stealthcopter** [comment]
Merged in, will be in 0.0.8 shortly.
