### ISSUE TITLE
Could not find com.scottyab:rootbeer-lib:0.0.8.

### ISSUE THREAD

**Issue by pdarcos** [scottyab/rootbeer#124]
Hi,

I was trying to test out the latest release in my project but jitpack doesn't seem to have the 0.0.8 version out yet.

Compiling with 0.0.7 works fine so I imagine there was some issue building 0.0.8 in jitpack?

Looking at https://jitpack.io/#scottyab/rootbeer it seems there was an error building 0.0.8

**Comment by stealthcopter** [comment]
@pdarcos Thanks for pointing this out, I imagine I've made a change that's causing something with jitpack not to package it properly. Looking at the logs I'm not really sure why, but I'll try and debug it. Will update once I know more

**Comment by stealthcopter** [comment]
Ok I've fixed it, what a nightmare. Anyone looking please don't blame me for the state of all the git commits and changes...

Note to self: login to jitpack and trigger a rebuild manually next time as it was caching failed artifacts.
