### ISSUE TITLE
Unable to get v0.0.8 from maven

### ISSUE THREAD

**Issue by cyberrob** [scottyab/rootbeer#127]
Thanks for new release v0.0.8 but still can't synced from [maven](https://search.maven.org/search?q=a:rootbeer-lib)

@scottyab Could you please check if it's been updated? Thank you!

**Comment by scottyab** [comment]
Thanks for flaggin, I having a few issues with the upload.

**Comment by mitchryanjusay** [comment]
Hi @scottyab just following up when can v0.0.8 be placed in maven.

**Comment by scottyab** [comment]
It's been year or so since the last update and struggling with the upload to nexus repo. The `uploadArchives` seems to have disappeared or rather it's not actually doing the upload. I'm not sure what's changed in this regard please bear with I have limited time to fault find.

**Comment by scottyab** [comment]
Confirmed https://search.maven.org/artifact/com.scottyab/rootbeer-lib/0.0.8/aar
