### ISSUE TITLE
Hisense TV being reported as rooted

### ISSUE THREAD

**Issue by deepak-pk** [scottyab/rootbeer#128]
Hi Team,
We got a few examples where customers that are using a Hisense TV receive an error that the app does not work on a rooted device upon launching our app. We are checking for rooted devices using your library. Customers also mentioned that it was working before but now the following error appears. Is there any change in how the check is being done for Hisense TV models? 

The following are the tv device models that have reported this issue.

Customer #1
TV model: Hisense 55RG Android 8.0
Android Version: 8.0.0
kernel Version: 3.18.66
Built: OTT1.180130.001

Customer #2
TV model: Hisense 55RG TV
Android Version: 8.0.0
kernel Version: 3.18.66
Built: OTT1.180130.001

Customer #3
TV model: Hisense TV
Android Version: 8.0.0
kernel Version: unknown

**Comment by stealthcopter** [comment]
@deepak-pk do you have access to the logs for any of these devices? Without more information we won't know if this is a false positive or not.

Otherwise if you have access to one of these TVs you could run the sample application from the play store and see if it believes the devices are rooted again uploading the logs from that he will help us figure out what's going on.

Thanks

**Comment by deepak-pk** [comment]
Does your sample app log the device info ? 
where to find the logs? 
is it in android studio console?

I can see your sample in here: https://play.google.com/store/apps/details?id=com.scottyab.rootbeer.sample

Is this available for Android TV in android tv playstore app?

**Comment by stealthcopter** [comment]
@deepak-pk Yes the sample app will log the the details of why we believe the device was rooted. A screenshot would certainly help as it'd tell us which test was failing. The app should be available for TVs however I've not personally tested this as I don't have access to an android tv. 

For a future enhancement, I'll have a look at adding an option to the sample app to export the logs for easier debugging.

**Comment by deepak-pk** [comment]
Hi @stealthcopter I have made a pull request with support for Android TV devices. 
https://github.com/scottyab/rootbeer/pull/129
