### ISSUE TITLE
Xiaomi Redmi Note 5 (MIUI 11.0.3) get a false positive

### ISSUE THREAD

**Issue by mgaire** [scottyab/rootbeer#137]
Hi,

We are testing our app on several android device, and we have detected a false positive only on Xiaomi Redmi Note 5 with MIUI 11.0.3 (management root apps).
Other android devices is on MIUI 11.0.3 or MIUI 11.0.4, and no problem.

I use the 0.0.8 version of RootBeer.

**Comment by vdaita** [comment]
Hi @mgaire  - is there anything you did to solve this issue?

**Comment by mgaire** [comment]
Hi @vdaita , the SuperSU application was installed on this device, after uninstalling the check is ok.

Best regards

**Comment by stealthcopter** [comment]
This is good to know, thanks for updating.
