### ISSUE TITLE
checkForBinary(BINARY_BUSYBOX) return falsepositives or not?

### ISSUE THREAD

**Issue by suba13556** [scottyab/rootbeer#151]
In RootBeer v0.0.8.2 library busybox check was removed in IsRooted()  to overcome false positives.. I want to find presence of busybox binary in my device(need not include the binary that the manufacture was leaved).. 

whether possible to detect root by using rootBeer.isRootedWithBusyBoxCheck() or checkForBinary(BINARY_BUSYBOX)  without falsepositives?

**Comment by stealthcopter** [comment]
You are free to use the busybox checks, but as you've stated the manufacturer may leave it on the device and it isn't always indicative of a root device (hence why we removed it)
