### ISSUE TITLE
Android-X

### ISSUE THREAD

**Issue by WuglyakBolgoink** [scottyab/rootbeer#153]
Hallo guys,

I have a small question. Do I need to do something for supporting android-x by using rootbeer lib?

In my case I work with cordova framework for mobile apps. 

And this is recomendation form cordova:

> ## Added AndroidX Support
> 
> AndroidX is the new and improved namespace for the `Android Support Libraries`. The original support libraries are no longer maintained.
> 
> It is recommended to use `AndroidX` so that your app is running the latest support libraries but, by default, `Cordova has AndroidX support disabled for compatibility with existing plugins`.
> 
> A lot of the Android supported plugins are still using the old support libraries which can not build when using the AndroidX support libraries. It is recommended to research each plugin to see if they support AndroidX before enabling this feature.
> 
> It is recommended for plugin developers to start migrating to support AndroidX. App developers could also use `Jetifier` to automatically migrates their `existing third-party libraries to use AndroidX`.
> 
> You can enable this feature by setting the `AndroidXEnabled` preference to true in config.xml.
> 
> `<preference name="AndroidXEnabled" value="true" />`
> 
> If you were previously using the `cordova-plugin-androidx` plugin to enable AndroidX support, this plugin is no longer needed with this preference flag.
> 
> The `cordova-plugin-androidx-adapter` plugin can be used to migrate the legacy references to the new AndroidX references.

- https://www.npmjs.com/package/cordova-plugin-androidx
- https://www.npmjs.com/package/cordova-plugin-androidx-adapter

this two plugins are just fallbacks...

**Comment by stealthcopter** [comment]
@WuglyakBolgoink this library has 0 dependencies, so the androidx change doesn't affect us.

**Comment by WuglyakBolgoink** [comment]
@stealthcopter ok, thank you!
