### ISSUE TITLE
Memory access violation after updating the library 0.0.8

### ISSUE THREAD

**Issue by yokeshezumalai** [scottyab/rootbeer#154]
Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7242cbf660 in tid 21642.

Any idea why?

But only in production build.

**Comment by stealthcopter** [comment]
Is this occurring frequently? If so please provide more detailed crash logs.

**Comment by scottyab** [comment]
This looks like a stale issue closing. Please reopen if still an issue on 0.1.1
