### ISSUE TITLE
CustomRootBeer.checkForDangerousProps (CheckRootTask.java) Getting NullPointerException

### ISSUE THREAD

**Issue by DheerajKumarSingh** [scottyab/rootbeer#156]
Hi Team,
I am getting this crash in samsung device android 10 version only , I am using **com.scottyab:rootbeer-lib:0.0.6** version. I am getting this error once i upgrade my API target version from 28 to 29.

Devices are mention bellow.
Galaxy S20 5G
Galaxy S10e
Galaxy S20+ 5G
Galaxy S10 5G
Galaxy Note10+ 5G
Galaxy S20

**Comment by stealthcopter** [comment]
This is useless without crashlogs

**Comment by DheerajKumarSingh** [comment]
String[] lines = propsCustomReader();  throw NullPointerException for crash log please check the attachment.
![scrren1](https://user-images.githubusercontent.com/19371801/96959255-373e5980-151d-11eb-84b2-22209533e01c.png)

**Comment by NotNotMarshall** [comment]
> String[] lines = propsCustomReader(); throw NullPointerException, For crash log please check the attachment.
> ![scrren1](https://user-images.githubusercontent.com/19371801/96959255-373e5980-151d-11eb-84b2-22209533e01c.png)

Use the latest version, you're still on 0.0.6 and the current one is 0.0.8

**Comment by stealthcopter** [comment]
Sounds like we've fixed this already then, cheers NotNotMarshall. Please reopen if I am mistake.
