### ISSUE TITLE
Getting false positive on various Galaxy models

### ISSUE THREAD

**Issue by NotNotMarshall** [scottyab/rootbeer#158]
I am using the latest version of your library but I have received more than 20 reports from my users telling that they get a root warning message, and most of them use Samsung Galaxy devices.

The devices which had the false positive are:
Galaxy S6 Edge
Galaxy S7 and S8
Galaxy Note 20
Galaxy S10
Galaxy S20

**Comment by NotNotMarshall** [comment]
@scottyab !!!!!

**Comment by scottyab** [comment]
Hey @NotNotMarshall I've deleted your other comment as it's not helpful here. You'll need to provide us we some more details on the root check that's failing. Please reopen when you have some details to share. Thanks
