### ISSUE TITLE
Obfuscation issue

### ISSUE THREAD

**Issue by libyasdf** [scottyab/rootbeer#160]
After I Obfuscate it.

* Unpacking the Android app APK file. 
* Using the JD-GUI utility to decompile the binary.

Using the JD-GUI utility, the application was successfully decompiled into useable source code as 
shown below:

<img width="309" alt="Screen Shot 2021-02-28 at 8 47 48 PM" src="https://user-images.githubusercontent.com/26648844/109419019-3905b580-7a06-11eb-9b2b-64fe9f6d09e4.png">

How can I Obfuscate "RootBeer" "RootBeerNative" "scottyab" in the source code?

**Comment by stealthcopter** [comment]
I'm afraid we dont have a good solution for you, but if you find a way please submit a pull request. 

You can probably write some proguard rules to obsfuscate the com.scottyab.rootbeer package name, but may be tricker for the native library. One alternative would be to take the source code and include it in your application but modify the package and class names yourself. This is obviously not ideal tho...
