### ISSUE TITLE
Plans for a new Release

### ISSUE THREAD

**Issue by TheFrozenDuck** [scottyab/rootbeer#162]
The last official release has been about a year ago. In the meantime some important commits (additional bad package definitions, additional compile options) have been added. Any chance we get a new official release and a version bump to 0.0.9 anytime soon?

**Comment by Re1r0** [comment]
Sooo, @scottyab  are we getting a release anytime soon? :)

**Comment by scottyab** [comment]
Sorry for the delay. 0.0.9 has been published to maven central. Thanks for the interest and the prompt for the release
