### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by xAffan** [scottyab/rootbeer#163]
I'm a complete noob here. Just want to know how can I access the logs so I can properly unroot my phone?

**Comment by stealthcopter** [comment]
@xAffan I'm afraid we can't really help you. RootBeer is just a detection library / app, I would suggest posting this to an android forum somewhere.

**Comment by xAffan** [comment]
Have you read what I said? I want to see the "logs" created by rootbeer.
How do I do that?!

**Comment by stealthcopter** [comment]
Currently, there is no way to do this in our sample application unless you plug it into a computer and use `adb logcat` to read them.

**Comment by xAffan** [comment]
Thanks, I'll check it out. That was what I needed to know. Perhaps you can
add this to readme.md so newcomers/beginners know how to get a log before
opening a issue(just a suggestion)

**Comment by stealthcopter** [comment]
@xAffan The plan is to add it into the sample app as an option. But yeah, I'll update the readme for now. Thanks
