### ISSUE TITLE
RootBeer sample fail on SElinux check

### ISSUE THREAD

**Issue by david-lev** [scottyab/rootbeer#168]
Hi, I have new Samsung galaxy S21, running Android 11, This is an original device that has never been rooted or with unlocked bootloader. 
but in the new version of rootbeer I get message says that my device has been rooted.

I checked the device settings (Settings > About phone > software information > Se for Android status) and there's SElinux is on Enforcing mode. So what could be the problem, maybe an error in the checking process?

There are a lot of apps that use the rootbeer library to get root indication, which means I can't use them if the problem isn't resolved.

![Screenshot_20210509-120850_Settings.jpg](https://user-images.githubusercontent.com/42866208/117567132-481e7900-b0c3-11eb-9f3c-9fa9b6c0d22b.jpg)
![Screenshot_20210509-120842_RootBeer Sample.jpg](https://user-images.githubusercontent.com/42866208/117567137-4d7bc380-b0c3-11eb-9fe0-efc818897c57.jpg)

**Comment by VD171** [comment]
Selinux is returning a false positive.

**Comment by stealthcopter** [comment]
@VD171 sorry I didn't quite get that. What is Selinux returning?

**Comment by VD171** [comment]
> @VD171 sorry I didn't quite get that. What is Selinux returning?

The app is showing SELinux as disabled even though it is not.

**Comment by scottyab** [comment]
Removed the Selinux method in 0.1.1 given it's not accessible on later versions of Android and is not "truly" an isRooted indicator. Thanks for flaggin this issue.
