### ISSUE TITLE
new root dedction

### ISSUE THREAD

**Issue by amk316** [scottyab/rootbeer#169]
i updated stc pay yesterday to 1.6 and it found my magisk canary (22105)
the think i notes is the (isolated) is added to the app !!!

rootbeer did not detected root after hiding!

**Comment by scottyab** [comment]
Hey @amk316 I'm not really clear what you're asking? could you give us some more context?

**Comment by amk316** [comment]
if i delete the magisk app it pass
it seams it can find root with a hidden magisk app!!!

**Comment by stealthcopter** [comment]
@amk316 It would be interesting to know what they're doing, but reverse engineering other applications is a bit beyond the scope of this project. However, if you are or anyone else is interested in doing it, we would love to know the result.

It could be that they are using SafetyNet, see here for an [example](https://github.com/scottyab/safetynethelper) application.

I'm going to close this issue as there's likely not much more we can do here, but please raise another PR if you have more information.
