### ISSUE TITLE
Nexus 6 evaluated as rooted

### ISSUE THREAD

**Issue by martinpoulsen** [scottyab/rootbeer#17]
I face a problem appearing similar to https://github.com/scottyab/rootbeer/issues/13 for a regular Nexus 6 on a non-rooted (and non-tampered-with) Android 6.0.1 system. Specifically, `checkForRWPaths()` returns true when hitting these variable assignments:
- `line: "none /dev/cpuset cgroup rw,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent 0 0"`
- `pathToCheck: "/sbin"`

![rootbeercheckforrwpaths](https://cloud.githubusercontent.com/assets/2430314/14602015/c364e39c-0565-11e6-986f-37ecc2b21237.png)

**Comment by martinpoulsen** [comment]
I think instead of checking whether the entire `line` contains `pathToCheck`, it should only look for `pathToCheck` within the mount point `line.split(" ")[1]`

**Comment by scottyab** [comment]
should be fixed in #18
