### ISSUE TITLE
Gerrit Vulnerability on Scanning Rootbeer integrated APK

### ISSUE THREAD

**Issue by Harsh2098** [scottyab/rootbeer#174]
On scanning our APK with `rootbeer` library already integrated, we found out Gerrit vulnerability in `lib/arm64-v8a/libtool-checker.so`:

Vulnerability level: low risk
Threat classification: M2: Insecure data storage
Cause: Native library does not open stack protection
Vulnerability impact: reduce attack costs

Our investigation suggests that the following configuration should be added in `.mk` to enable stack protection.

LOCAL_CFLAGS +=-fstack-protector-all

**Comment by stealthcopter** [comment]
@Harsh2098 can you make sure you've tested the latest version as this is something we fixed recently.
https://github.com/scottyab/rootbeer/blob/master/rootbeerlib/src/main/cpp/CMakeLists.txt

**Comment by Harsh2098** [comment]
@stealthcopter Thanks for quick reply. Let me update version to the latest release on our side.
