### ISSUE TITLE
MagiskHide passed all checks

### ISSUE THREAD

**Issue by AlirezaIvaz** [scottyab/rootbeer#176]
When Magisk Hide is off, the demo app can detect that the device is rooted, but when it is on, all checks are passed!

**Comment by stealthcopter** [comment]
This is expected, they are hiding from us.

**Comment by Electric1447** [comment]
![THEBOX_1](https://user-images.githubusercontent.com/36371414/127905209-0346e0e6-0b91-42e4-bbb3-5c66ce2a0525.jpg)

**Comment by AkshayJainG** [comment]
Maybe have a look at this 
https://github.com/darvincisec/DetectMagiskHide
