### ISSUE TITLE
SeLinux test is inverted

### ISSUE THREAD

**Issue by fmcnunes** [scottyab/rootbeer#179]
Hi,

SeLinux test in file CheckForRootWorker.kt appers to be wrong:

Line 24    RootItemResult("SE linux Flag Is Enabled", Utils.isSelinuxFlagInEnabled()),

It should be:

Line 24    RootItemResult("SE linux Flag Is Enabled", **!** Utils.isSelinuxFlagInEnabled()),

SeLinixFlagedEnabled() result true is a good result, means thatSecurity-Enhanced Linux (ro.build.selinux set to 1)  is activated,  but the sign it as a bad result.

Best regards
Fernando Nunes

**Comment by VD171** [comment]
Selinux is returning a false positive.

**Comment by scottyab** [comment]
Removed the Selinux method in 0.1.1 given it's not accessible on later versions of Android and is not "truly" an isRooted indicator. Thanks for flagging this issue.
