### ISSUE TITLE
Is selinux flag giving a false positive?

### ISSUE THREAD

**Issue by test-pad** [scottyab/rootbeer#183]
Hi. I have a Samsung note 20 ultra. I am not sure why rootbeer sample app indicates that my phone is rooted. My phone is not rooted.

I have used other apps like root checker, advanced root checker and root beer fresh and all indicate my phone is not rooted.

May I know if there are ways to check if there is a bug or there are something that is causing the false positive? Some screenshots below for your reference.

Thank you very much.

![Screenshot_20210917-072615_RootBeer Sample.jpg](https://user-images.githubusercontent.com/50765030/133868021-1442f368-f95f-4888-bf1d-55f5a691cc40.jpg)

![Screenshot_20210917-072639_Settings.jpg](https://user-images.githubusercontent.com/50765030/133868029-7720ace1-a7d5-4498-a258-12c30dfa7dff.jpg)

![Screenshot_20210917-072708_Settings.jpg](https://user-images.githubusercontent.com/50765030/133868135-a2f5a009-29c0-4c97-b46e-f8261028eaf7.jpg)

**Comment by grubeli** [comment]
There are old issues talking about this: https://github.com/scottyab/rootbeer/issues/179

Looks like no one maintains the project any more

**Comment by scottyab** [comment]
Hey @grubeli sorry it feels that way. Merged your PR thanks for the contribution.

**Comment by roshaan-sadapay** [comment]
@scottyab when you guys are gonna release this version?

**Comment by ale5000-git** [comment]
@scottyab
Reading over the internet I have found `ro.build.selinux` is unreliable, it may be 0 and still SELinux is enforced or it may also be missing completely.

It is more reliable to execute `/system/bin/getenforce` that return `Enforcing`, or read `/sys/fs/selinux/enforce` that return `1`.

**Comment by mohamedebrahim96** [comment]
@ale5000-git 

Could you please fix the code in pull request so that lib owner can merge

**Comment by malikzype** [comment]
Facing same issue. False Positive

**Comment by agnostic-apollo** [comment]
@scottyab You may wanna check https://github.com/kdrag0n/safetynet-fix/pull/166#issuecomment-1509789489 and remove the check altogether.

**Comment by VD171** [comment]
Selinux is returning a false positive.

**Comment by scottyab** [comment]
We have removed the Selinux method in 0.1.1 given it's not accessible on later versions of Android and is not "truly" an isRooted indicator. Thanks for flagging this issue.
