### ISSUE TITLE
isRooted() can bypass by decomple way 

### ISSUE THREAD

**Issue by hosseinkhojany** [scottyab/rootbeer#185]
i decompiled my apps and i found isRooted method from my source code and i change result of this to always false it bypass very easy

**Comment by stealthcopter** [comment]
There isn't a massive amount we can do to prevent this, decompilation is always going to be able to defeat our checks. Obfuscation can help, but it would only work to slightly slow down the process. Another method to help is to add signature verification into your applications then after recompilation this check would fail.

I'm going to close this as we don't really see it as an issue, at least not one we can solve. But feel free to comment again if you wish to discus it further.
