### ISSUE TITLE
Samsung S20+ false positive

### ISSUE THREAD

**Issue by wolfich** [scottyab/rootbeer#187]
Hi!
Currently I have Samsung SM-G985F/DS,
Knox is OK and Samsung payments are working.
But sample app reports rooting.
Log and OS details will be  in comments.

**Comment by wolfich** [comment]
![Screenshot_20220103-011703_RootBeer Sample.jpg](https://user-images.githubusercontent.com/9077605/147891903-aa6fd90e-d0f4-48a4-a906-fb57df3b64db.jpg)
![Screenshot_20220103-012501_Settings.jpg](https://user-images.githubusercontent.com/9077605/147891906-26ad0154-51a3-41c0-a13b-c2874a6f4ab8.jpg)

**Comment by alangaelrojas** [comment]
The same happens using Samsung galaxy tab s7 
![image](https://user-images.githubusercontent.com/16097757/158084916-1ce5a891-d0da-4336-8f96-cba2f5511c08.png)

**Comment by dannkunt** [comment]
+1

**Comment by malikzype** [comment]
+1

**Comment by Damaj301damaj-lol** [comment]
+1

**Comment by KasunHasanga** [comment]
+1

**Comment by scottyab** [comment]
We have removed the Selinux method in 0.1.1 given it's not accessible on later versions of Android and is not "truly" an isRooted indicator. Thanks for flagging this issue.
