### ISSUE TITLE
DexGuard config

### ISSUE THREAD

**Issue by scottyab** [scottyab/rootbeer#2]
Provide some adv DexGuard config to mask the rootcheck method calls and the const.java.

**Comment by kmno** [comment]
0.0.8 has a weird problem with dexguard!
we have to downgrade to 0.0.7 to ignore this problem ...

**Comment by scottyab** [comment]
> weird problem with dexguard

Hey @kmno can you share any details on the issue?

**Comment by MahmoudElFerekh** [comment]
@scottyab when using DexGuard, the App is crashing when using version 0.0.8 of Rootbeer, while version 0.0.7 works fine

**Comment by scottyab** [comment]
@MahmoudElFerekh @kmno I believe the best course of action is to contact DexGuard support for assistance. They can see the code of rootbeer where as we don't have DexGuard licence to fault find.

**Comment by scottyab** [comment]
Closing based on the above. Needs more input either from DexGuard or OP with 0.1.1
