### ISSUE TITLE
Old Sample app on Google Play

### ISSUE THREAD

**Issue by hosek** [scottyab/rootbeer#201]
Hi, 
on Gplay, there is old version of the app with wrong SE Linux check (that missing negation)

Btw it would be better to distinguish between checks done in Sample app vs library.

Maybe add **isRooted()**  check as example of output of the library and add note thet SE Linux is just informative ?

**Comment by scottyab** [comment]
The sample has been removed from google play for the time being. When it we republish it'll be the latest version. Thanks for flagging this.
