### ISSUE TITLE
For RW Paths detected, I don't understand

### ISSUE THREAD

**Issue by CrimsonBloodfang** [scottyab/rootbeer#219]
![Screenshot_20231125-150907_RootBeer_Sample](https://github.com/scottyab/rootbeer/assets/68450471/a0b5b9cd-e647-4db1-b443-d67de550d374)

`adb shell ls -ld /system /system/bin /system/sbin /system/xbin /vendor/bin /sbin /etc /system/etc /sys /proc /dev`

Output:
```
drwxr-xr-x  22 root root  4080 2023-11-25 18:45 /dev
lrwxrwxrwx   1 root root    11 1970-01-01 08:00 /etc -> /system/etc
dr-xr-xr-x 442 root root     0 1970-01-01 08:00 /proc
drwxr-xr-x   4 root root   620 2023-11-25 18:14 /sbin
dr-xr-xr-x  14 root root     0 2023-11-25 18:13 /sys
drwxr-xr-x  20 root root  4096 2023-06-20 14:34 /system
drwxr-x--x   4 root shell 8192 2023-11-25 14:58 /system/bin
drwxr-xr-x  19 root root  4096 2023-06-20 14:34 /system/etc
drwx------   2 root root    40 2023-11-25 18:13 /system/xbin
drwxr-xr-x   3 root shell 8192 2018-12-24 17:45 /vendor/bin
ls: /system/sbin: No such file or directory
```
But I did the same command to an unrooted phone and they have similar output for permissions and yet For RW Paths is passed or undetected in that unrooted phone. 

I don't understand the difference and the process on how it's getting detected yet having the same permissions.
- Am I using the wrong command to check?
- Is it a mount problem?
- What else?

**Comment by pyerix** [comment]
> I finally know why. It's a secret.

bruh what? I have the same problem and do not understand why
