### ISSUE TITLE
ONEPLUS 3 Phone  no check

### ISSUE THREAD

**Issue by laizhouzhang** [scottyab/rootbeer#22]
ONEPLUS 3 phone  no root，but checked is rooted

**Comment by xDragonZ** [comment]
You should provide more information about this, such as screenshot of the result

**Comment by stealthcopter** [comment]
This is likely due to them leaving a busybox binary (or similar) in the production build of their Oxygen rom, as they did with the OnePlus 2.

**Comment by aritraroy** [comment]
I am using this library to detect root in my app, and it works great except this scenario. It falsely detects that OnePLus 3 has root, while it doesn't have root. I can understand the issue you have mentioned that they have left busybox binary in the rom, but is there a workaround for this? This is pretty important for my app to detect root with as much accuracy as possible?

**Comment by stealthcopter** [comment]
I suggest you create your own method similar to the isRooted method in the base of the library. But comment out / remove the call to check for the busybox binary.

Something like this should work:

`    public boolean isRooted() {
        RootBeer rootBeer = new RootBeer(Context context);
        boolean rootManagement = rootBeer.detectRootManagementApps();
        boolean potentiallyDangerousApps = rootBeer.detectPotentiallyDangerousApps();
        boolean suBinary = rootBeer.checkForBinary("su");
        boolean busyboxBinary = false; // rootBeer.checkForBinary("busybox");
        boolean dangerousProps = rootBeer.checkForDangerousProps();
        boolean rwSystem = rootBeer.checkForRWPaths();
        boolean testKeys = rootBeer.detectTestKeys();
        boolean testSuExists = rootBeer.checkSuExists();
        boolean testRootNative = rootBeer.checkForRootNative();

        return rootManagement || potentiallyDangerousApps || suBinary
                || busyboxBinary || dangerousProps || rwSystem || testKeys || testSuExists || testRootNative;
    }`

**Comment by aritraroy** [comment]
Thanks for the suggestion. Will do that.
