### ISSUE TITLE
Could not resolve com.scottyab:rootbeer-lib:0.0.9 on windows

### ISSUE THREAD

**Issue by JaineSaconi** [scottyab/rootbeer#225]
When I try to build my app on Windows I get the following error

![image](https://github.com/scottyab/rootbeer/assets/52785316/9b0af111-8449-4e43-9853-3d018be05035)

On Mac and Linux it works

**Comment by scottyab** [comment]
Hi, thanks for the report however this looks like a local issue that your build cannot find/resolve the rootbeer dependency and I'm not sure how to assist with this without more info. The repo has undergone significant updates to Gralde/Java etc with a new version update coming soon, in the mean time suggest moving to the latest version https://mvnrepository.com/artifact/com.scottyab/rootbeer-lib/0.1.0
