### ISSUE TITLE
Riddled with false-positives. Scrub this harmful project from existence.

### ISSUE THREAD

**Issue by WAZAAAAA0** [scottyab/rootbeer#226]
This library has clearly been a net negative for humanity.

The irony of being falsely flagged as rooted... and needing root to [bypass it](<https://github.com/gauravssnl/BypassRootCheckPro?tab=readme-ov-file#screenshots>) 😂 
One can just take a [quick](<https://github.com/scottyab/rootbeer/issues?q=>) [glance](<https://github.com/KimChangYoun/rootbeerFresh/issues?q=>) at the issues to understand the situation. I'll repost some tragic examples:

> The NJTransit app is using your library to detect root, and the Play Store is riddled with reviews of false positives. It's preventing people from accessing tickets they legitimately purchased.

> personally the problem is blocking for me because French banks use your lib for their applications

> The app MobilePay is the ubiquitous mobile-payments app here.I think that the vast majority of persons in Denmark use this app daily or weekly for payments.

> I am developper for a big android App. ATInternet stats show that all BlackView 8000 phones are detected as root.

> Yeah, there are 1 million ways to detect Magisk, and yet you choose to falsely flag all Unix sockets that are 32 bytes long. Great job 👍

These cases aren't rare: I'm also affacted on TWO non-rooted phones of different brands with locked bootloaders using stock ROM (SELinux flag. The app doesn't even bother spelling it right and calls it "SE linux" btw).

Who's to blame, some random unpaid incompetent open source devs who abandoned their ѕhіttу harmful project in a broken state, or governments and companies for actually using it?
But let's imagine for a moment the project gets fixed and is able to miraculously detect root with perfect accuracy... what's the end goal? An easy way for corporations to arbitrarily restrict the people's freedoms on their own devices?
An app to simply test if your root works correctly for *troubleshooting reasons* exists already ([Root Verifier](<https://f-droid.org/it/packages/com.abcdjdj.rootverifier/>)) and supports Android 2.2+

This app/library is a lose-lose situation for everyone. It has done enough damage already, so do the right thing: cast it into the fire. Destroy it.

**Comment by scottyab** [comment]
I appreciate it can be frustrating when consumer apps degrade or block functionality based on the results of rootbeer. But it's not really down to rootbeer to be accountable for that, this is open source and apps can implement whatever checks they like. I've recently improved the readme to make it a bit clearer what each check is doing and to further emphaise that this is an indication of root and not to treat the result of the rootbeer check as 100% truth. 

I'm closing this issue as it feels more like a rant/troll post rather than something that is trying to improve things.
