### ISSUE TITLE
Failed to promote to production on Maven Central due to missing sources

### ISSUE THREAD

**Issue by scottyab** [scottyab/rootbeer#236]
**Describe the bug/feature request/question**

I'm getting the following error when attempting to close the published 0.1.1 item to promote to production. 

> maven central Event: Failed: "Sources Validation" Missing: no main jar artifact found in folder

<img width="1189" alt="image" src="https://github.com/user-attachments/assets/c03edafc-754a-4a46-a9ab-abf3ad3af907">

Snapshot publishing seems to work aok, see [here](https://oss.sonatype.org/content/repositories/snapshots/com/scottyab/rootbeer-lib/0.1.1-SNAPSHOT/). 

Currently looking into this but posting here for visibility.

**Comment by scottyab** [comment]
Pom packaging was `jar` but should be `aar` - thanks to Niall for spotting this

**Comment by NityaSantosh26** [comment]
@scottyab, Thanks for releasing 0.1.1. But I still can't use the latest version and here is the log from jitpack.io. There's some gradle task failing.
https://jitpack.io/com/github/scottyab/rootbeer/0.1.1/build.log

**Comment by scottyab** [comment]
Hey @NityaSantosh26 so we seem to have broken jitpack.io builds with the move to the gradle built-in maven publishing support as now the signing details are required for release builds. This isn't a bad thing per se and to me, it seems this is better from a security/authenticity point of view - but sorry if this has broken your build. 

Can you drop jitpack.io in favour of Maven Central?  you might need to reorder them in your repository definition.  

If not then maybe you can reopen and rename #235 as "Jitpack.io releases are no longer supported since 0.1.1" and we look to prioritise this if more people flag this as an issue.
