### ISSUE TITLE
Rootbeer not working on Android 15 with page size 16kb

### ISSUE THREAD

**Issue by IkeaOlof** [scottyab/rootbeer#239]
When using Android 15 with page size of 16kb, the libToolChecker library doesnt work.
The logs received are the following:
 `“RootBeer: checkForRootNative() [445]
  We could not load the native library to test for root”`

**How to reproduce.**
Flash a phone with Android 15 and page size of 16kb, or create a matching emulator.
Use the lib by calling RootBeer(context).isRooted

**Rootbeer Library Version**
Library Version : 0.1.0

**Device Information**
- Device: Android emulator
- OS: Android 15, page size 16kb

**Comment by scottyab** [comment]
Thank you for flagging this. Please can you update to the latest release. 0.1.1 this issue was specifically fixed as noted in the release notes. If you are still seeing the issue in latest please let us know. Thanks

**Comment by IkeaOlof** [comment]
Im so sorry, I totally missed that. Thanks for a quick reply. I will update to latest version of the lib and create a new issue if i find something. 🤗
