### ISSUE TITLE
Logging cannot be deactivated

### ISSUE THREAD

**Issue by aippisch** [scottyab/rootbeer#25]
I use your library in my Android project. I would like to suggest that there is the possibility to deactivate logging. In QLog the value for Logging Level is hardcoded to "ALL".
Also, the logging message (level INFO) I get is

```
I/RootBeer: LOOKING FOR BINRARY: /system/bin/su Absent :(
```

binRary instead of binary.

**Comment by scottyab** [comment]
Hey @aippisch, thanks for the suggestion and the spelling error spot. I LOL'd at binRary! Please feel free to send us a pull request with the changes and we'll review and likely accept.

**Comment by WuglyakBolgoink** [comment]
Hi guys and @scottyab!

There are 2x PR .. any news? will be nice to fix this issue quickly 👍 

Thank you!
