### ISSUE TITLE
Release rootbeer-lib:0.0.5 and new Sample app to Playstore

### ISSUE THREAD

**Issue by scottyab** [scottyab/rootbeer#43]
* Bundle recent changes to new version rootbeer-lib:0.0.5
* Add Change log
* Upload release version of Sample app to Google Play

**Comment by ShadowWarrior0** [comment]
This release has already occurred and this issue can be closed.

I would like to see another issue opened for the next release of the library/sample-app.

**Comment by stealthcopter** [comment]
0.0.7 is uploaded to play store now so closing.
