### ISSUE TITLE
Showing rooted in my redmi note 3

### ISSUE THREAD

**Issue by Akshay-Kumar-S** [scottyab/rootbeer#56]
Hi,

My redmi note 3 is not rooted, but the method rootBeer.isRooted() return true.

Thanks
Akshay

**Comment by madevelopers** [comment]
Install Rootbeer sample app from play store and run it. It will show you what detection was flagged. See False positive section on the README file https://github.com/scottyab/rootbeer/blob/master/README.md

**Comment by stealthcopter** [comment]
Closing as no response, assume it's all ok now. Please feel free to reopen if you're still having issues.
