### ISSUE TITLE
Error Android NDK: Application targets deprecated ABI(s): armeabi

### ISSUE THREAD

**Issue by silwar** [scottyab/rootbeer#59]
Hi 
I am getting following error after integration of Rootbeer lib in my app
**Error:(XX) Android NDK: Application targets deprecated ABI(s): armeabi    
Error:(XX) Android NDK: Support for these ABIs will be removed in a future NDK release.**
Although app is compiling and running as it is.
What could be the possible solution for this error?

**Comment by stealthcopter** [comment]
What version of the NDK do you have installed?
The application.mk file targets all ABIs
`APP_ABI := all`
So will attempt to make all platforms.

**Comment by silwar** [comment]
@stealthcopter NDK version i am using is 16.0.4293906 rc1

**Comment by pjhjohn** [comment]
@silwar Looks like `armeabi` is deprecated since [NDK r16 beta1](https://github.com/android-ndk/ndk/wiki/Changelog-r16-beta1)

> Support for ARM5 (armeabi) is deprecated. It will no longer build by default with ndk-build, but is still buildable if it is explicitly named, and will be included by "all" and "all32".

Since you explicitly named `armeabi` or using either one of `all` and `all32`, the compiler still runs with it. If you downgrade NDK version back to r15 or lower, the error message will not be shown. Otherwise, you gotta prepare for the deprecation or dropping support for `armeabi`

**Comment by stealthcopter** [comment]
@pjhjohn Thanks, From reading that snippet, it seems that it should only show a warning when building armeabi, so I'm not sure why it is returning an error in this case. Do you have any compiler flags that would cause it to be strict about warnings?
I've got to admit I'm no expect in the abi types available to android, so if there is a better replacement for `all` I'd love your advice! I am reticent to change it to `all64` in case this would exclude any current 32bit processors.

**Comment by Yumee** [comment]
same problem and more infomation after  ``` deprecated ABI``` ,i got this ```Error:unknown target CPU 'armv7-a'```, and I can't run app~

**Comment by nugula** [comment]
I have same problem. So, I changed APP_ABI value to all in Android.mk.
Now, It's ok. It works android studio 2.3 and 3.0 both.

**Comment by stealthcopter** [comment]
Rewritten how the ndk compiles the app now, should be fixed in latest release 0.0.7
