### ISSUE TITLE
RootBeer is crashed on RIM devices running Android apps.

### ISSUE THREAD

**Issue by kkamaraj** [scottyab/rootbeer#6]
Used RootBeer library to detect whether an android device was rooted or not. Apparently RIM Blackberry allows android app to run on them and the library crashed on those devices. 

Caused by java.lang.NullPointerException
java.util.Scanner. (Scanner.java:226)
java.util.Scanner. (Scanner.java:210)
com.scottyab.rootbeer.RootBeer.mountReader (RootBeer.java:208)
com.scottyab.rootbeer.RootBeer.checkForRWPaths (RootBeer.java:251)
com.scottyab.rootbeer.RootBeer.isRooted (RootBeer.java:41)

**Comment by scottyab** [comment]
fixed in PR from @stealthcopter
