### ISSUE TITLE
unable to run the project 

### ISSUE THREAD

**Issue by yogeshmishrikotkar** [scottyab/rootbeer#60]
I have imported the rootbeer project. But after running this project i am getting below error 

Error:error: unable to execute command: program not executable
Error:error: linker command failed with exit code 1 (use -v to see invocation)
Error:org.gradle.internal.UncheckedException: Build command failed.
Error:error: unable to execute command: program not executable
Error:error: linker command failed with exit code 1 (use -v to see invocation)
Error:Build command failed.
Error:error: unable to execute command: program not executable
Error:error: linker command failed with exit code 1 (use -v to see invocation)

can anyone help?

**Comment by stealthcopter** [comment]
You got the NDK installed? If so what version?

**Comment by stealthcopter** [comment]
Closing as no reply, please reopen if you're still having problems.
