### ISSUE TITLE
Is it good to call isRootedWithoutBusyBoxCheck() instead isRooted()?

### ISSUE THREAD

**Issue by Bajranghudda1** [scottyab/rootbeer#61]
When I am using isRooted(), my most of the device showing it's rooted, so I decided to use isRootedWithoutBusyBoxCheck() as stated in https://github.com/scottyab/rootbeer/issues/39 .

So what is exactly busy box binary?

I'm new please suggest my any good way, Thanks happy coding :-)

**Comment by stealthcopter** [comment]
Basically [busybox](https://en.wikipedia.org/wiki/BusyBox) is a collection of tools wrapped up into a binary (executable code). It's typically installed along with root as it provides a set of tools that don't rely on the platform having them available or may have different versions. 

During our testing it became apparent that some manufacturers were leaving busybox binary in the production build of their roms, for this reason we added a method that ignores this check as it wasn't always an indication of root for these devices.

**Comment by Bajranghudda1** [comment]
@stealthcopter
Thanks for your quick reply :-)
You people are really doing great 1+
