### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by KursX** [scottyab/rootbeer#65]
Fatal Exception: java.lang.NullPointerException
src == null
java.util.Scanner.<init> (Scanner.java:226)
java.util.Scanner.<init> (Scanner.java:210)
com.scottyab.rootbeer.RootBeer.propsReader(RootBeer.java)
com.scottyab.rootbeer.RootBeer.checkForDangerousProps(RootBeer.java)

**Comment by stealthcopter** [comment]
This is fixed in the feature/gradle-update branch and there is a PR open, as soon as it's merged I will push a new release out

**Comment by stealthcopter** [comment]
Fixed in 0.0.7 release
