### ISSUE TITLE
Motorola Moto Z is determined Root wrongly

### ISSUE THREAD

**Issue by hajk1** [scottyab/rootbeer#69]
I have a Moto Z Cell phone for a year. Although it is original but some payment applications which make use of rootbeer indicate my phone as ROOTed and do not let installation on my phone.
One reason is my phone has su command however it is not executable as it is indicated on 'Commands' section of 'Eric Gruber' article .

**Comment by stealthcopter** [comment]
In the upcoming release we've removed busybox from the default root checks, this should hopefully fix many of the problems with false positives. I'm closing this issue but please re-open if you get a false positive with 0.0.8 onwards.
Thanks!
