### ISSUE TITLE
Nullpointer Exception in checkForRWPaths

### ISSUE THREAD

**Issue by atmaramthakur** [scottyab/rootbeer#71]
String[] lines = mountReader(); is returning null in some devices. 

Need to add a null check before for loop.

**Comment by stealthcopter** [comment]
Thanks for the report, confirmed and fixed

**Comment by atmaramthakur** [comment]
Thanks, I will wait for it.

Regards,
Atmaram

**Comment by atmaramthakur** [comment]
HI,
Any update on the release

the snapshot doesn't work in my case. Getting error :

Failed to resolve: com.github.scottyab:rootbeer:master-SNAPSHOT

Regards,
Atmaram

**Comment by stealthcopter** [comment]
Hi @atmaramthakur, Sorry for the delay, I'm still waiting for my changes to be checked so we can merge the PR. 

I got the branch wrong on the gradle url above. It should be:
    implementation 'com.github.scottyab:rootbeer:feature~gradle-update-SNAPSHOT'

**Comment by stealthcopter** [comment]
Fixed in 0.0.7 release
