### ISSUE TITLE
False positive: Elephone R9

### ISSUE THREAD

**Issue by gnuyork** [scottyab/rootbeer#81]
Just wanted to inform you about another false positive that could be added to the Wiki:

An unrooted Elephone R9 with Android SDK Version 25 (Android 7.1.1) gives the following results

isRooted(): true
isRootedWithoutBusyBoxCheck(): true
canLoadNativeLibrary(): true
checkForNativeLibraryReadAccess(): true
checkForDangerousProps(): true

checkForBusyBoxBinary(): false
checkForMagiskBinary(): false
checkForRootNative(): false
checkForRWPaths(): false
checkForSuBinary(): false
checkSuExists(): false
detectPotentiallyDangerousApps(): false
detectRootCloakingApps(): false
detectRootManagementApps(): false
detectTestKeys(): false

**Comment by stealthcopter** [comment]
In the upcoming release we've removed busybox from the default root checks, this should hopefully fix many of the problems with false positives. I'm closing this issue but please re-open if you get a false positive with 0.0.8 onwards.
Thanks!
