### ISSUE TITLE
Possible false positive Huawei Mate 10 lite (HWRNE)

### ISSUE THREAD

**Issue by carl0047** [scottyab/rootbeer#83]
Hi guys I got some possible false positive reports of Huawei Mate 10 lite (HWRNE) phone. Anyone else with this issue?

**Comment by thubalek-inloop** [comment]
Do both `RootBeer.isRootedWithoutBusyBoxCheck()` and `RootBeer.isRooted()` return false positive?

**Comment by stealthcopter** [comment]
In the upcoming release we've removed busybox from the default root checks, this should hopefully fix many of the problems with false positives. I'm closing this issue but please re-open if you get a false positive with 0.0.8 onwards.
Thanks!
