### ISSUE TITLE
Limit jniLibs to only armeabi-v7a

### ISSUE THREAD

**Issue by juan9506** [scottyab/rootbeer#85]
Hi, I have one app that have compatibility with all devices, but only when there's no native libraries but armeabi-v7a, after adding iroot plugin (that is a wrapper of this one), it creates several other architectures libtool-checker.so files (mips, mips64, x86_64 ...) and this is making my app crash.
Do you know how to limit the plugin so the only generated native library is for armeabi-v7a?
I've been looking through all the code and didn't found where it defines these architectures.
I have already ask the same question here: https://github.com/WuglyakBolgoink/cordova-plugin-iroot/issues/13#issue-380330251
Thanks.

**Comment by ligi** [comment]
maybe you want to use the workaround I use here: 

https://github.com/walleth/walleth/blob/47b76953527975e140f6dfc6ae49f4977dfeabf0/app/build.gradle#L200

this removes all native checks - context #80

**Comment by juan9506** [comment]
I solved this by using the following plugin: https://github.com/Jween/android-soexcluder
what it does is removing and including only the desired .so files, so in my case, I only include the armeabi-v7a .so file and removed all the others.

**Comment by jhscheer** [comment]
There's an abiFilter in [rootbeerlib/src/main/jni/Application.mk](https://github.com/scottyab/rootbeer/blob/593ff5670c7286faf69ca188b977c7d3d1a478c1/rootbeerlib/src/main/jni/Application.mk)
to tell Gradle to only build outputs for the desired ABIs.
So next time just drop the ABIs you don't need, e.g.:
`APP_ABI := armeabi-v7a arm64-v8a x86 x86_64`
`APP_ABI := armeabi-v7a`
