### ISSUE TITLE
Root detection giving false results for some devices

### ISSUE THREAD

**Issue by srikanth4b9** [scottyab/rootbeer#86]
Hi,

Devices like LYF and Lenovo devices are giving rooted device, even this OS comes with default mobile.

/data/local/
/sbin/
/system/bin/
/system/xbin/

**Comment by jdmartins** [comment]
I'm also experiencing some false positives on  **android**

List of affected devices so far:
* Samsung Galaxy A8 @ _probably_ **Android 6**
* Lenovo TAB 4 10 @ **Android 7.1**

**Comment by stealthcopter** [comment]
In the upcoming release we've removed busybox from the default root checks, this should hopefully fix many of the problems with false positives. I'm closing this issue but please re-open if you get a false positive with 0.0.8 onwards.
Thanks!
