### ISSUE TITLE
False positive  Samsung A5 2016 Android 5.1.1

### ISSUE THREAD

**Issue by CodeFries** [scottyab/rootbeer#87]
I have another false positive: Samsung A5 2016 running Android 5.1.1

Checking it with isRootedWithoutBusyBoxCheck

**Comment by jdmartins** [comment]
@CodeFries any luck with `isRootedWithoutBusyBoxCheck` ?

**Comment by ashbizmobile** [comment]
@CodeFries What was the result when you tried `isRootedWithoutBusyBoxCheck` ?

**Comment by stealthcopter** [comment]
In the upcoming release we've removed busybox from the default root checks, this should hopefully fix many of the problems with false positives. I'm closing this issue but please re-open if you get a false positive with 0.0.8 onwards.
Thanks!
