### ISSUE TITLE
Galaxy Note 9

### ISSUE THREAD

**Issue by gerostam** [scottyab/rootbeer#89]
Hi all,

Brand new Galaxy Note 9 is detected as rooted. Please check it!

**Comment by WuglyakBolgoink** [comment]
@gerostam work again?

**Comment by gerostam** [comment]
It was not working for a Note 9 in Saudi Arabia, but I found a friend in Greece with this device and worked fine so I suppose it is a problem with that specific device or he used an app that rooted his phone without him understanding it.
