### ISSUE TITLE
Ready for 64 Bit devices?

### ISSUE THREAD

**Issue by gnuyork** [scottyab/rootbeer#90]
More a question than an issue: Is this project ready to be used with 64 bit devices?
https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html

**Comment by xgouchet** [comment]
From what I've seen, the project does provide the following architectures (cf : https://github.com/scottyab/rootbeer/tree/master/rootbeerlib/src/main/jniLibs) : 
 - x86
 - x86_64
 - armeabi-v7a
 - arm64-v8a
This means that indeed, Rootbeer does support 64-bit for both ARM and x86 architecture.

**Comment by stealthcopter** [comment]
@xgouchet is correct. Architectures can be found directly in the make file here:
https://github.com/scottyab/rootbeer/blob/master/rootbeerlib/src/main/jni/Application.mk
