### ISSUE TITLE
Application crashed with signal SIGSEGV

### ISSUE THREAD

**Issue by SergeyPolokhach** [scottyab/rootbeer#92]
Hello, thank you for the library.
When using your library, the application crashes on some Samsung devices.
```
0 | at java.lang.ProcessManager.exec(Native Method)
1 | at java.lang.ProcessManager.exec(ProcessManager.java:209)
2 | at java.lang.Runtime.exec(Runtime.java:168)
3 | at java.lang.Runtime.exec(Runtime.java:123)
4 | at com.scottyab.rootbeer.b.g(RootBeer.java:337)
5 | at com.scottyab.rootbeer.b.a(RootBeer.java:45)
```
Using in Activity:

````
private fun checkRoot() {
        val rootBeer = RootBeer(this)
        if (rootBeer.isRooted) {
              ...
        }
 }
```

**Comment by cocr1742** [comment]
@SergeyPolokhach What Device/API are you using?

**Comment by stealthcopter** [comment]
Can we get a full crash report, device name, android version. Have you done any obfuscation?  `com.scottyab.rootbeer.b.a` looks like maybe some renaming has occurred.

**Comment by stealthcopter** [comment]
I'm going to close this as we don't have enough information, please feel free to reopen if you are still having this issue.
