### ISSUE TITLE
Does rootbeer detect Cynagenmod.superuser and any Chainfire package i.e Super

### ISSUE THREAD

**Issue by anshulagarwal92** [scottyab/rootbeer#93]
I want to detect any chainfire package or cynagenmod.supersu on jailbroken devices. Can anyone suggest how can i do it.

**Comment by EarlOfEgo** [comment]
Rootbeer checks for the package `eu.chainfire.supersu` with the method `detectRootManagementApps`.

**Comment by stealthcopter** [comment]
Just from a cursory look it seems like cynagenmod.supersu doesn't use a constant package name in order to bypass simple detection. So there isn't much more we can do until we add some more advanced root detection methods.
