### ISSUE TITLE
Detection might not be accurate

### ISSUE THREAD

**Issue by mike14u** [scottyab/rootbeer#95]
The `isRooted` method detects some false positive sometimes, we used the SuperSU app to determine if the phone is rooted or not, as compared to RootBeer and it gave a more accurate result. We did this on a brand new Galaxy S10+

**Comment by stealthcopter** [comment]
In the upcoming release we've removed busybox from the default root checks, this should hopefully fix many of the problems with false positives. I'm closing this issue but please re-open if you get a false positive with 0.0.8 onwards.
Thanks!
